[package]
name = "wiremock-header-matcher-bug"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = { version = "0.12.4" }
tokio = { version = "1.37.0" }
wiremock = { version = "0.6.0" }
